[project]
name = "langgaph-course"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Eden Marco", email = "emarco177@gmail.com" }
]

dependencies = [
    "langchain",
    "langgraph",
    "langchain-openai",
    "python-dotenv",
    "black",
    "isort",
    "langchain-tavily"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"