[project]
name = "langgraph-course"
version = "0.1.0"
description = ""
authors = [
    {name = "Eden Marco", email = "emarco177@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain>=0.3.25",
    "langchain-openai>=0.3.18",
    "langchain-tavily>=0.2.0",
    "langgraph>=0.4.7",
    "python-dotenv>=1.1.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "isort>=6.0.1",
]

